---
# tasks file for pg

- name: epel-install
  yum:
    name:  
      - nano
      - mc
    state: present

- name: pgs
  copy:
    src: pgdg-redhat-all.repo
    dest: /etc/yum.repos.d/pgdg-redhat-all.repo

- name: nginx and postgres
  yum:  
    name:  
      - postgresql14-server
      - wget
      - unzip
    state: present 





# - name: "Initialize PostgreSQL"
#   ansible.builtin.command: /usr/pgsql-14/bin/postgresql-14-setup initdb
#   notify:
#     - restart p


- name: "script"
  command: "systemctl start postgresql-14.service "
  become_user: root

- name: fyf
  copy:
    src: demo-small-20170815.sql
    dest: /var/lib/pgsql/demo-small-20170815.sql

- name: "script"
  ansible.builtin.shell: psql -f /var/lib/pgsql/demo-small-20170815.sql
  become_user: postgres


# - name: Create appclient user with SCRAM-hashed password
#   community.postgresql.postgresql_user:
#     name: alaliceice
#     password: "alice"
#   environment:
#     PGOPTIONS: "-c password_encryption=scram-sha-256"
#   become_user: postgres


- name: create postgresql user
  postgresql_user:
    user: "alice"
    password: "alice"
    role_attr_flags: "CREATEDB,NOSUPERUSER"
  become: true
  become_user: postgres
  tags: db

- name: 
  postgresql_owner:
    db: demo
    new_owner: alice
    obj_name: demo
    obj_type: table
  tags: db


  

